### ISSUE TITLE
Install Sentry

### ISSUE THREAD

**Issue by ainowy** [ainowy/SEBC#25]

**Comment by ainowy** [comment]
In this issue, I had to create the Sentry database as it wasnt previously configured in order to set up the Sentry service. Also, I could see that there werent databases named "web_logs" or "customers" but tables, so I granted privileges on Sentry specifying tables

**Comment by ainowy** [comment]
Also, I would like to comment that in the beeline.png it can be appreciated the full command in order to be shown 10 results "select * from web_logs limit 10"; However, as the full output was too long, I captured only the first lines. Hope that is fine

**Comment by mfernest** [comment]
This wasn't a well-written challenge. Didn't think it through as well as I thought. Thanks for bearing with it.
